/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-07 03:31:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1598427227931L));
    _jspx_dependants.put("jar:file:/C:/workspace/adminAM/AMDashboard/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("=========================================================\r\n");
      out.write("* * Black Dashboard - v1.0.1\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write("* Product Page: https://www.creative-tim.com/product/black-dashboard\r\n");
      out.write("* Copyright 2019 Creative Tim (https://www.creative-tim.com)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* Coded by Creative Tim\r\n");
      out.write("\r\n");
      out.write("=========================================================\r\n");
      out.write("\r\n");
      out.write("* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>\r\n");
      out.write("    Black Dashboard by Creative Tim\r\n");
      out.write("  </title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <div class=\"main-panel\">\r\n");
      out.write(" \r\n");
      out.write("      <div class=\"modal modal-search fade\" id=\"searchModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"searchModal\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"inlineFormInputGroup\" placeholder=\"SEARCH\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                <i class=\"tim-icons icon-simple-remove\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- End Navbar -->\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card card-chart\">\r\n");
      out.write("              <div class=\"card-header \">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-sm-6 text-left\">\r\n");
      out.write("                    <h5 class=\"card-category\">Total Shipments</h5>\r\n");
      out.write("                    <h2 class=\"card-title\">Performance</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"btn-group btn-group-toggle float-right\" data-toggle=\"buttons\">\r\n");
      out.write("                      <label class=\"btn btn-sm btn-primary btn-simple active\" id=\"0\">\r\n");
      out.write("                        <input type=\"radio\" name=\"options\" checked>\r\n");
      out.write("                        <span class=\"d-none d-sm-block d-md-block d-lg-block d-xl-block\">Accounts</span>\r\n");
      out.write("                        <span class=\"d-block d-sm-none\">\r\n");
      out.write("                          <i class=\"tim-icons icon-single-02\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </label>\r\n");
      out.write("                      <label class=\"btn btn-sm btn-primary btn-simple\" id=\"1\">\r\n");
      out.write("                        <input type=\"radio\" class=\"d-none d-sm-none\" name=\"options\">\r\n");
      out.write("                        <span class=\"d-none d-sm-block d-md-block d-lg-block d-xl-block\">Purchases</span>\r\n");
      out.write("                        <span class=\"d-block d-sm-none\">\r\n");
      out.write("                          <i class=\"tim-icons icon-gift-2\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </label>\r\n");
      out.write("                      <label class=\"btn btn-sm btn-primary btn-simple\" id=\"2\">\r\n");
      out.write("                        <input type=\"radio\" class=\"d-none\" name=\"options\">\r\n");
      out.write("                        <span class=\"d-none d-sm-block d-md-block d-lg-block d-xl-block\">Sessions</span>\r\n");
      out.write("                        <span class=\"d-block d-sm-none\">\r\n");
      out.write("                          <i class=\"tim-icons icon-tap-02\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                      </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"chart-area\">\r\n");
      out.write("                  <canvas id=\"chartBig1\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"card card-chart\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"card-category\">Total Shipments</h5>\r\n");
      out.write("                <h3 class=\"card-title\"><i class=\"tim-icons icon-bell-55 text-primary\"></i> 763,215</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"chart-area\">\r\n");
      out.write("                  <canvas id=\"chartLinePurple\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"card card-chart\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"card-category\">Daily Sales</h5>\r\n");
      out.write("                <h3 class=\"card-title\"><i class=\"tim-icons icon-delivery-fast text-info\"></i> 3,500€</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"chart-area\">\r\n");
      out.write("                  <canvas id=\"CountryChart\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"card card-chart\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"card-category\">Completed Tasks</h5>\r\n");
      out.write("                <h3 class=\"card-title\"><i class=\"tim-icons icon-send text-success\"></i> 12,100K</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"chart-area\">\r\n");
      out.write("                  <canvas id=\"chartLineGreen\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6 col-md-12\">\r\n");
      out.write("            <div class=\"card card-tasks\">\r\n");
      out.write("              <div class=\"card-header \">\r\n");
      out.write("                <h6 class=\"title d-inline\">Tasks(5)</h6>\r\n");
      out.write("                <p class=\"card-category d-inline\">today</p>\r\n");
      out.write("                <div class=\"dropdown\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-link dropdown-toggle btn-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                    <i class=\"tim-icons icon-settings-gear-63\"></i>\r\n");
      out.write("                  </button>\r\n");
      out.write("                  <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#pablo\">Action</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#pablo\">Another action</a>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#pablo\">Something else</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body \">\r\n");
      out.write("                <div class=\"table-full-width table-responsive\">\r\n");
      out.write("                  <table class=\"table\">\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">Update the Documentation</p>\r\n");
      out.write("                          <p class=\"text-muted\">Dwuamish Head, Seattle, WA 8:47 AM</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\" checked=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">GDPR Compliance</p>\r\n");
      out.write("                          <p class=\"text-muted\">The GDPR is a regulation that requires businesses to protect the personal data and privacy of Europe citizens for transactions that occur within EU member states.</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">Solve the issues</p>\r\n");
      out.write("                          <p class=\"text-muted\">Fifty percent of all respondents said they would be more likely to shop at a company </p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">Release v2.0.0</p>\r\n");
      out.write("                          <p class=\"text-muted\">Ra Ave SW, Seattle, WA 98116, SUA 11:19 AM</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">Export the processed files</p>\r\n");
      out.write("                          <p class=\"text-muted\">The report also shows that consumers will not easily forgive a company once a breach exposing their personal data occurs. </p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <div class=\"form-check\">\r\n");
      out.write("                            <label class=\"form-check-label\">\r\n");
      out.write("                              <input class=\"form-check-input\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                              <span class=\"form-check-sign\">\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          <p class=\"title\">Arival at export process</p>\r\n");
      out.write("                          <p class=\"text-muted\">Capitol Hill, Seattle, WA 12:34 AM</p>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"td-actions text-right\">\r\n");
      out.write("                          <button type=\"button\" rel=\"tooltip\" title=\"\" class=\"btn btn-link\" data-original-title=\"Edit Task\">\r\n");
      out.write("                            <i class=\"tim-icons icon-pencil\"></i>\r\n");
      out.write("                          </button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6 col-md-12\">\r\n");
      out.write("            <div class=\"card \">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h4 class=\"card-title\"> Simple Table</h4>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                  <table class=\"table tablesorter \" id=\"\">\r\n");
      out.write("                    <thead class=\" text-primary\">\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th>\r\n");
      out.write("                          Name\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <th>\r\n");
      out.write("                          Country\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <th>\r\n");
      out.write("                          City\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <th class=\"text-center\">\r\n");
      out.write("                          Salary\r\n");
      out.write("                        </th>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Dakota Rice\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Niger\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Oud-Turnhout\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $36,738\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Minerva Hooper\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Curaçao\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Sinaai-Waas\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $23,789\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Sage Rodriguez\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Netherlands\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Baileux\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $56,142\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Philip Chaney\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Korea, South\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Overland Park\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $38,735\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Doris Greene\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Malawi\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Feldkirchen in Kärnten\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $63,542\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Mason Porter\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Chile\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Gloucester\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $78,615\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Jon Porter\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Portugal\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                          Gloucester\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"text-center\">\r\n");
      out.write("                          $98,615\r\n");
      out.write("                        </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"fixed-plugin\">\r\n");
      out.write("    <div class=\"dropdown show-dropdown\">\r\n");
      out.write("      <a href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("        <i class=\"fa fa-cog fa-2x\"> </i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <ul class=\"dropdown-menu\">\r\n");
      out.write("        <li class=\"header-title\"> Sidebar Background</li>\r\n");
      out.write("        <li class=\"adjustments-line\">\r\n");
      out.write("          <a href=\"javascript:void(0)\" class=\"switch-trigger background-color\">\r\n");
      out.write("            <div class=\"badge-colors text-center\">\r\n");
      out.write("              <span class=\"badge filter badge-primary active\" data-color=\"primary\"></span>\r\n");
      out.write("              <span class=\"badge filter badge-info\" data-color=\"blue\"></span>\r\n");
      out.write("              <span class=\"badge filter badge-success\" data-color=\"green\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"adjustments-line text-center color-change\">\r\n");
      out.write("          <span class=\"color-label\">LIGHT MODE</span>\r\n");
      out.write("          <span class=\"badge light-badge mr-2\"></span>\r\n");
      out.write("          <span class=\"badge dark-badge ml-2\"></span>\r\n");
      out.write("          <span class=\"color-label\">DARK MODE</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"button-container\">\r\n");
      out.write("          <a href=\"https://www.creative-tim.com/product/black-dashboard\" target=\"_blank\" class=\"btn btn-primary btn-block btn-round\">Download Now</a>\r\n");
      out.write("          <a href=\"https://demos.creative-tim.com/black-dashboard/docs/1.0/getting-started/introduction.html\" target=\"_blank\" class=\"btn btn-default btn-block btn-round\">\r\n");
      out.write("            Documentation\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"header-title\">Thank you for 95 shares!</li>\r\n");
      out.write("        <li class=\"button-container text-center\">\r\n");
      out.write("          <button id=\"twitter\" class=\"btn btn-round btn-info\"><i class=\"fab fa-twitter\"></i> &middot; 45</button>\r\n");
      out.write("          <button id=\"facebook\" class=\"btn btn-round btn-info\"><i class=\"fab fa-facebook-f\"></i> &middot; 50</button>\r\n");
      out.write("          <br>\r\n");
      out.write("          <br>\r\n");
      out.write("          <a class=\"github-button\" href=\"https://github.com/creativetimofficial/black-dashboard\" data-icon=\"octicon-star\" data-size=\"large\" data-show-count=\"true\" aria-label=\"Star ntkme/github-buttons on GitHub\">Star</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
